# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14916a36b3dbc7b1630677a0d8e14d2a7e1d865251e72d3d06a438aeb608167b244b678274ea7833fe1b37cbf932e6c13d30bc11786a64a68e0e91ef302446f2

test:
  secret_key_base: 8e546b2dead56cc1d837e854c2b6968c1abc40672154554b44db2e2bc26c822ce080dac8469a7b10fd64b43b154efacbe616a9fac6b35779753053eeac6b79e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
